FROM openjdk:8
ADD . /src
WORKDIR /src
##To change user to a non root user
RUN groupadd -r ms-accelerator && useradd --no-log-init -r -m -g ms-accelerator ms-accelerator && chown -R ms-accelerator:ms-accelerator /src
USER ms-accelerator
CMD ["./gradlew", "clean", "ms-accelerator-component-test:build", "--info"]